steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    waitFor: ['build']
    id: 'push'
    args: [ 'push', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}' ]


## Deploy container image to Cloud Run Public Instance
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    waitFor: ['push']
    id: 'deploy public'
    entrypoint: gcloud
    args: [ 'run', 'deploy', 'streamlit-test-public', '--image', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest',
            '--region', 'us-central1',
            '--memory', '4Gi',
            '--cpu', '2',
            '--platform', 'managed', 
            '--allow-unauthenticated', 
            '--session-affinity',
            '--min-instances=1', '--cpu-boost',
            '--max-instances=2'
    ]

## Deploy container image to Cloud Run behind IAP
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    waitFor: ['push']
    id: 'deploy behind iap'
    entrypoint: gcloud
    args: [ 'run', 'deploy', 'streamlit-test-private', '--image', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest',
            '--region', 'us-central1',
            '--memory', '4Gi',
            '--cpu', '2',
            '--platform', 'managed', 
            '--no-allow-unauthenticated',
            '--ingress', 'internal-and-cloud-load-balancing', 
            '--session-affinity',
            '--min-instances=1', '--cpu-boost',
            '--max-instances=2',
            '--set-env-vars', '_IAP_AUDIENCE=$_IAP_AUDIENCE'
    ]

substitutions:
  _IMAGE_NAME: streamlit-headerinspection-image
options:
  logging: CLOUD_LOGGING_ONLY
